# This file is expected to fail ‚ùå upon push until you fix the bug
# You successfully completed this level when this file pass üü¢ upon push
name: HACK - Jarvis Gone Wrong

on:
  push:
    paths:
      - ".github/workflows/jarvis-code.yml"

jobs:
  jarvis:
    runs-on: ubuntu-latest
    permissions:
      contents: read
    steps:
      - name: Check out code
        uses: actions/checkout@v3

      - name: Check for insecure actions
        run: |

         curl https://www.githubstatus.com/api/v2/status.json
